### ISSUE TITLE
versioned releases

### ISSUE THREAD

**Issue by msftcangoblowm** [sphinx-notes/pages#42]
The page is published to ```https://[user name].github.io/[repo name]/```

There is no option to publish a versioned release

In this [workflow](https://glebbahmutov.com/blog/versioned-doc-pages), the versioned release is made possible by ```peaceiris/actions-gh-pages@v3``` and inputs:

```
publish_dir: ./public
destination_dir: 1.0.0
```
Which would produces our coveted versioned site

```https://[user name].github.io/[repo name]/1.0.0/```

**Comment by msftcangoblowm** [comment]
What is the tradeoffs between actions/deploy-pages@v4 and peaceiris/actions-gh-pages@v3 ??

**Comment by msftcangoblowm** [comment]
Just to future proof. multiple language support

```https://[user name].github.io/[repo name]/en/stable/```

**Comment by SilverRainZ** [comment]
~~Just because actions/deploy-pages@v4 is an official action and does not know about peaceiris/actions-gh-pages@v3. I think it is ok to switch to the latter one (without breaking anything), PR is welcome.~~

Sorry for misleading you, I use actions/deploy-pages@v4 just because it supports [Publishing with a custom GitHub Actions workflow](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow) and peaceiris/actions-gh-pages@v3 does not.

You can still use version releases by  [Publishing from a branch (classical)](https://github.com/sphinx-notes/pages?tab=readme-ov-file#publishing-from-a-branch-classical)
